name: Build Cliente Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: update into machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ~/arquitetodigital
          pm2 stop arquitetodigital-frontend
          pm2 stop arquitetodigital-backend
          git pull origin main
          cd frontend
          npm install
          npm run build
          cd ..
          cd backend
          npm install
          npm run build
          npx sequelize db:migrate
          npx sequelize db:seed
          pm2 start arquitetodigital-frontend
          pm2 start arquitetodigital-backend
