# PARA USAR PRECISA DA EXTENSÃO DO VS CODE "REST Client"

#Variaveis
@baseUrl = http://localhost:8080
# @baseUrl = https://apidev.pressticket.com.br
@token = 6175c0d0-acd5-4776-95a9-592c795da986
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3RlckFkbWluIiwicHJvZmlsZSI6Im1hc3RlcmFkbWluIiwiaWQiOjIsImlhdCI6MTczMzY4OTk2NiwiZXhwIjoxNzMzNjkzNTY2fQ.g_jJs3vovlU5i9sS0IUoJ3Ew_m7W8GzqjWd-kieFFpc

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzI4ODUzMzQsImV4cCI6MTczMzQ5MDEzNH0.RwuRIufYUB9dQZQg0aeaVtnOryn-sESNL1mFlShmBM4

### (Login) Teste da Rota POST /auth/login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "masteradmin@pressticket.com.br",
  "password": "masteradmin"
}

### Teste da Rota POST /auth/refresh_token
POST {{baseUrl}}/auth/refresh_token
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

### (Enviar Mensagem) Teste da Rota POST /api/messages/send
POST {{baseUrl}}/api/messages/send
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "number": "5522992463080",
  "body": "Mensagem de Teste da API com user e queue atualizado",
  "userId": "1",
  "queueId": "2",
  "whatsappId": "1"
}

### (Listar Personalizações) Teste da Rota GET /personalizations
GET {{baseUrl}}/personalizations
Content-Type: application/json

### (Criar ou Atualizar Dados da Empresa) Teste da Rota PUT /personalizations/:theme/company
PUT {{baseUrl}}/personalizations/light/company
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "company": "Press Ticket",
  "url": "https://pressticket.com.br"
}

### (Criar ou Atualizar Cores) Teste da Rota PUT /personalizations/:theme/colors
PUT {{baseUrl}}/personalizations/light/colorS
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "primaryColor": "#ffffff",
  "secondaryColor": "#0000ff",
  "backgroundDefault": "#ff00ff",
  "backgroundPaper": "#00ff00"
}

### (Criar ou Atualizar Logos) Teste da Rota PUT /personalizations/:theme/logos
PUT {{baseUrl}}/personalizations/light/logos
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "favico": "teste.ico",
  "logo": null,
  "logoTicket": null
}

### (Remover Personalização) Teste da Rota DELETE /personalizations/:theme
DELETE {{baseUrl}}/personalizations/light
Authorization: Bearer {{token2}}
Content-Type: application/json
