# PARA USAR PRECISA DA EXTENSÃO DO VS CODE "REST Client"

#Variaveis
# @baseUrl = http://localhost:8080
@baseUrl = https://devapi.pressticket.com.br
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlByZXNzLVRpY2tldCIsInByb2ZpbGUiOiJhZG1pbiIsImlkIjoxLCJpYXQiOjE3NDEzMDY0MTUsImV4cCI6MTc0MTMzNTIxNX0.l-mfrtfPH9dF7-WJqIGnyWxG2Uy7UdSVMVSJQqwWTRs
@token2 = 02d0f367-c6ce-4bfe-bfe1-20cc42836515

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzI4ODUzMzQsImV4cCI6MTczMzQ5MDEzNH0.RwuRIufYUB9dQZQg0aeaVtnOryn-sESNL1mFlShmBM4

### (Login) Teste da Rota POST /auth/login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@pressticket.com.br",
  "password": "258369"
}

### Teste da Rota POST /auth/refresh_token
POST {{baseUrl}}/auth/refresh_token
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

### (Enviar Mensagem) Teste da Rota POST /api/messages/send
POST {{baseUrl}}/api/messages/send
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "number": "5522999999999",
  "body": "Mensagem de Teste da API com user e queue atualizado",
  "userId": "1",
  "queueId": "2",
  "whatsappId": "1"
}

### (Listar Personalizações) Teste da Rota GET /personalizations
GET {{baseUrl}}/personalizations
Content-Type: application/json

### (Criar ou Atualizar Dados da Empresa) Teste da Rota PUT /personalizations/:theme/company
PUT {{baseUrl}}/personalizations/light/company
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "company": "Press Ticket",
  "url": "https://pressticket.com.br"
}

### (Criar ou Atualizar Cores) Teste da Rota PUT /personalizations/:theme/colors
PUT {{baseUrl}}/personalizations/light/colorS
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "primaryColor": "#ffffff",
  "secondaryColor": "#0000ff",
  "backgroundDefault": "#ff00ff",
  "backgroundPaper": "#00ff00"
}

### (Criar ou Atualizar Logos) Teste da Rota PUT /personalizations/:theme/logos
PUT {{baseUrl}}/personalizations/light/logos
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "favico": "teste.ico",
  "logo": null,
  "logoTicket": null
}

### (Remover Personalização) Teste da Rota DELETE /personalizations/:theme
DELETE {{baseUrl}}/personalizations/light
Authorization: Bearer {{token2}}
Content-Type: application/json

### (Listar Tickets Abertos) Teste da Rota GET /tickets/contact/${contactId}/open
GET {{baseUrl}}/tickets/contact/6/open
Authorization: Bearer {{token2}}
Content-Type: application/json

### (Listar Mensagens Send e Received) Teste da Rota GET /messages/count
GET {{baseUrl}}/messages/count
Authorization: Bearer {{token}}
Content-Type: application/json

### (Listar Mensagens Send e Received) Teste da Rota GET /messages/count?all=true
GET {{baseUrl}}/messages/count?all=true
Authorization: Bearer {{token}}
Content-Type: application/json

### (Listar Mensagens Send e Received) Teste da Rota GET /messages/count?userId=1
GET {{baseUrl}}/messages/count?userId=1
Authorization: Bearer {{token}}
Content-Type: application/json

### (Listar Mensagens Send e Received) Teste da Rota GET /messages/count?startDate=2025-01-01&endDate=2025-12-31
GET {{baseUrl}}/messages/count?startDate=2025-02-01&endDate=2025-02-18&&all=true
Authorization: Bearer {{token}}
Content-Type: application/json

### API Tokens Routes ###

### List all tokens
GET {{baseUrl}}/api-tokens
Authorization: Bearer {{token}}

### Create new token
POST {{baseUrl}}/api-tokens
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Test API Token",
    "permissions": ["create:messages", "create:medias", "read:whatsapps"]
}

### Get token by id
GET {{baseUrl}}/api-tokens/6
Authorization: Bearer {{token}}

### Delete token
DELETE {{baseUrl}}/api-tokens/2
Authorization: Bearer {{token}}

### Test API Token Authentication - List Whatsapps
GET {{baseUrl}}/whatsapp
x-api-token: 3136bb3d-9e7f-4340-9d64-d5bb4671e774

### Test API Token - Send Message
POST {{baseUrl}}/api/messages/v1/send
x-api-token: d836fd46-c69b-40c7-a4e3-f09a1c1c85d1
Content-Type: application/json

{
    "number": "5522992581997",
    "body": "Test message using API token",
    "userId": 1,
    "queueId": 1,
    "whatsappId": 1
}

### Test API Token - List Contacts
GET {{baseUrl}}/v1/contacts
x-api-token: e7f328b7-f271-451b-a3d1-0b6b95029033

### Test API Token - List Contacts with Pagination
GET {{baseUrl}}/v1/contacts?pageNumber=1&searchParam=Test
x-api-token: e7f328b7-f271-451b-a3d1-0b6b95029033

### Test API Token - Get Contact by ID
GET {{baseUrl}}/v1/contacts/50
x-api-token: e7f328b7-f271-451b-a3d1-0b6b95029033

### Test API Token - Create Contact
POST {{baseUrl}}/v1/contacts
x-api-token: e7f328b7-f271-451b-a3d1-0b6b95029033
Content-Type: application/json

{
  "name": "Test Contact API",
  "number": "5522995555555",
  "address": "rua",
  "email": "email",
  "extraInfo": [
    {
      "name": "custom_id",
      "value": "11111"
    },
    {
      "name": "country",
      "value": "Brazil"
    }
  ]
}

### Test API Token - Update Contact
PUT {{baseUrl}}/v1/contacts/50
x-api-token: e7f328b7-f271-451b-a3d1-0b6b95029033
Content-Type: application/json

{
  "name": "Felipe Freitas Dev",
  "email": "",
  "address": "",
  "number": "5511933464218"
}

### Test API Token - Delete Contact
DELETE {{baseUrl}}/v1/contacts/100
x-api-token: e7f328b7-f271-451b-a3d1-0b6b95029033

### Test API Token - Find Contact
POST {{baseUrl}}/v1/contact
x-api-token: e7f328b7-f271-451b-a3d1-0b6b95029033
Content-Type: application/json

{
  "number": "5522992581997"
}